### ISSUE TITLE
feat: consistent gallery and data table style

### ISSUE THREAD

**Issue by ivan0313** [ivan0313/Facial-Recognition-Database-Management-System#41]
Update the gallery component to have a consistent styling as data table, especially since #39 

This way the switch from gallery view to and from table view would be less jumpy. Both views would use the current style of the table view. 

Another advantage is that both views can share the same tool bar, as well as the pagination component.

**Comment by mrvishalsharma** [comment]
can i work on this issue?

**Comment by ivan0313** [comment]
sure @mrvishalsharma, do go ahead and take a look at the [contributing guidelines](https://github.com/ivan0313/Facial-Recognition-Database-Management-System/blob/main/CONTRIBUTING.md) if you haven't already. You're more then welcome to work on this issue :) 

I suppose we should cc @griseduardo to let him know you're working on this
